name: multiple_head_mlp
paras:
  # detect_or_not, num_fp, num_easy_fp, num_hard_fp
  backbone:
    config_file: model/mlp_backbone.yaml
    model_class: MLP

  fp_predictor:
    config_file: model/mlp_fp_prediction.yaml
    model_class: MLP

  all_num_predictor:
    config_file: model/mlp_all_num_prediction.yaml
    model_class: MLP

  hard_num_predictor:
    config_file: model/mlp_hard_num_prediction.yaml
    model_class: MLP

