dataset:
  config_file: dataset/scene_occ_heatmap.yaml
  dataset_class: FpSceneOccHeatmapDataset
logging:
  ckpt_eph_interval: 50
  path: ./output/log
  suffix: 'fp_scene_occ_heatmap'
model:
  config_file: model/multi_scale_cnn_cls.yaml
  model_class: MultiScaleCNNCls
training:
  device: 'cuda:0'
  epoch: 100
  loss_function:
    num_classes: 1
    alpha: 1.0
    beta: 0.1
  optimizer:
    paras:
      lr: 0.001
    type: Adam
  trainer_class: SceneOccClassifyHeatmapTrainer
  tensorboard_out_path: default
