# for running get_target_model_statistics_minist.py
dataset:
  config_file: dataset/minist.yaml
  dataset_class: MinistDataset
logging:
  ckpt_eph_interval: 2
  path: ''
  suffix: ''
model:
  config_file: model/cnn.yaml
  model_class: CNN
