dataset:
  config_file: dataset/scene_occ_heatmap.yaml
  dataset_class: TpFpSceneOccHeatmapDataset
logging:
  ckpt_eph_interval: 50
  path: ./output/log
  suffix: 'fp_scene_occ_tpfp_distribution'
model:
  config_file: model/multi_scale_cnn_cls.yaml
  model_class: MultiScaleCNNCls
training:
  device: 'cuda:0'
  epoch: 100
  loss_function:
    num_classes: 2
    alpha: 2.0
    beta: 0.01
  optimizer:
    paras:
      lr: 0.001
    type: Adam
  trainer_class: SceneOccClassifyHeatmapTrainer
  tensorboard_out_path: default
testing:
  cls_threshold: 0.05
  nms_iou_threshold: 0.1
