# for train vae-wgan model using main/train.py on minist dataset
dataset:
  config_file: dataset/only_box_dataset.yaml
  dataset_class: BoxOnlyDataset
logging:
  ckpt_eph_interval: 50
  path: ../output
  suffix: 'only_box'
model:
  config_file: model/multiple_head_mlp.yaml
  model_class: MultipleHeadMLP
training:
  device: 'cuda:0'
  epoch: 1000
  optimizer:
    paras:
      lr: 0.001
    type: RMSprop
  trainer_class: MultipleHeadMLPTrainer

