name: cnn
paras:
  input_size:
  - 3
  - 32
  - 32
  struct_list:
  - class: conv2d
    paras:
      act_func: relu
      chn_in: 3
      chn_out: 16
      kernel_size: 5
      padding: 2
      stride: 1
  - class: max_pool2d
    paras:
      kernel_size: 2
      stride: 2
  - class: conv2d
    paras:
      act_func: relu
      chn_in: 16
      chn_out: 32
      kernel_size: 5
      padding: 2
      stride: 1
  - class: max_pool2d
    paras:
      kernel_size: 2
      stride: 2
  - class: conv2d
    paras:
      act_func: relu
      chn_in: 32
      chn_out: 64
      kernel_size: 5
      padding: 2
      stride: 1
  - class: max_pool2d
    paras:
      kernel_size: 2
      stride: 2
  - class: linear
    paras:
      act_func: none
      node_num: 10

