dataset_class: BaselineKittiDataset
paras:
  batch_size: 32
  data_root: ./data
  for_train: True
  num_workers: 8
  shuffle: True
  target_model: pp
  sweeps_len: 1
  interface: False
  FP_distribution: False
  geometry:
    L1: -40
    L2: 40
    W1: 0.0
    W2: 70.4
    label_shape:
    - 352
    - 400
    ratio: 0.2