# for running get_target_model_statistics_cifar.py
dataset:
  config_file: dataset/cifar10.yaml
  dataset_class: Cifar10Dataset
logging:
  ckpt_eph_interval: 2
  path: ''
  suffix: ''
model:
  config_file: model/cnn.yaml
  model_class: CNN
