dataset:
  batch_size: 3
  config_file: /home/xlju/Project/ModelSimulator/utils/config/dataset/minist.yaml
  dataset_class: MinistDataset
logging:
  ckpt_eph_interval: 2
  path: ''
  suffix: ''
model:
  config_file: /home/xlju/Project/ModelSimulator/utils/config/model/samples/vae_gan.yaml
  model_class: VAEGANModel
training:
  device: 'cuda:0'
  epoch: 100
  optimizer:
  - name: encoder_opt
    paras:
      betas:
      - 0.5
      - 0.999
      lr: 0.0001
    type: Adam
  - name: discriminator_opt
    paras:
      betas:
      - 0.5
      - 0.999
      lr: 0.0001
    type: Adam
  trainer_class: VAEGANTrainer
