name: VAEGANModel
paras:
  submodules:
    discriminator:
      config_file: model/mlp.yaml
      model_class: MLP
    generator:
      config_file: model/vae.yaml
      model_class: VAE
    target_model:
      config_file: model/cnn.yaml
      model_class: CNN
      model_para_file: D:/1Pjlab/ModelSimulator/model_paras/param_minist_5.pt
