dataset_class: Kitti3dObjectDataset
paras:
  batch_size: 3
  data_root: ../data/kitti
  for_train: true
  num_workers: 4
  shuffle: true
  config_file: dataset/openpcd_dataset_related/kitti_dataset.yaml
  class_names: ['Car', 'Pedestrian', 'Cyclist']
