dataset:
  config_file: dataset/scene_occ_heatmap.yaml
  dataset_class: FpSceneOccHeatmapDataset
logging:
  ckpt_eph_interval: 50
  path: ./output/log
  suffix: 'scene_occ_generate_fp_cls'
model:
  config_file: model/vae_gan.yaml
  model_class: VAEGAN
training:
  device: 'cuda:0'
  epoch: 300
  optimizer:
  - name: encoder_opt
    paras:
      lr: 0.01
    type: Adam
  - name: discriminator_opt
    paras:
      lr: 0.002
    type: Adam
  trainer_class: VAEGANTrainerSceneOccGenFpCls
  tensorboard_out_path: default
