# for train vae-wgan model using main/train.py on minist dataset
dataset:
  config_file: dataset/fp_difficult_dataset.yaml
  dataset_class: FpDifficultDataset
logging:
  ckpt_eph_interval: 50
  path: ../output
  suffix: 'fp_difficult'
model:
  config_file: model/multiple_head_mlp.yaml
  model_class: MultipleHeadMLPFp
training:
  device: 'cuda:0'
  epoch: 1000
  optimizer:
    paras:
      lr: 0.0005
    type: Adam
  trainer_class: MultipleHeadMLPTrainer

