dataset:
  config_file: dataset/scene_occ_carla.yaml
  dataset_class: BaselineCarlaDataset
logging:
  ckpt_eph_interval: 50
  path: ./output/log
  suffix: 'baseline'
model:
  config_file: model/vae_gan.yaml
  model_class: VAEGAN
training:
  device: 'cuda:0'
  epoch: 300
  loss_function:
    num_classes: 1
    alpha: 2.0
    beta: 0.01
  optimizer:
  - name: encoder_opt
    paras:
      lr: 0.0005
    type: RMSprop
  - name: discriminator_opt
    paras:
      lr: 0.001
    type: Adam
  trainer_class: BaselineMMDDiscrimTrainer
  actor_feature_size: 256
  tensorboard_out_path: default
  FP_distribution: False
testing:
  cls_threshold: 0.5
  nms_iou_threshold: 0.2
