name: MultiScaleCNNCls
paras:
  submodules:
    backbone:
      config_file: model/multi_scale_cnn.yaml
      model_class: MultiScaleCNN
    head:
      config_file: model/perception_head.yaml
      model_class: DetectHead
    prediction: False
    MMD: False
    position_encoding: False