# for train vae-wgan model using main/train.py on minist dataset
dataset:
  config_file: dataset/cloud_point_dataset_fp.yaml
  dataset_class: FpCloudPointDataset
logging:
  ckpt_eph_interval: 50
  path: ../output
  suffix: 'cloud_point_fp'
model:
  config_file: model/vae_gan.yaml
  model_class: VAEGAN
training:
  device: 'cuda:0'
  epoch: 1000
  optimizer:
  - name: encoder_opt
    paras:
      lr: 0.0001
    type: Adam
  - name: discriminator_opt
    paras:
      lr: 0.0001
    type: Adam
  trainer_class: VAEGANTrainerCloudPointFP
  tensorboard_out_path: default