name: cnn
paras:
  input_size:
  - 3
  - 352
  - 400
  struct_list:
  - class: conv2d
    paras:
      act_func: relu
      chn_in: 3
      chn_out: 8
      kernel_size: 5
      padding: 1
      stride: 4
  - class: max_pool2d
    paras:
      kernel_size: 2
      stride: 2
  - class: conv2d
    paras:
      act_func: relu
      chn_in: 8
      chn_out: 16
      kernel_size: 3
      padding: 1
      stride: 2
  - class: linear
    paras:
      act_func: relu
      node_num: 512
  - class: linear
    paras:
      act_func: relu
      node_num: 64
  - class: linear
    paras:
      act_func: sigmoid
      node_num: 1
