dataset_class: FpSceneOccNuScenesDataset
paras:
  nuscenes_type: v1.0-mini
  batch_size: 4
  data_root: D:/1Pjlab/ADModel_Pro/data
  for_train: True
  num_workers: 1
  shuffle: True
  FP_distribution: False
  geometry:
    L1: -40
    L2: 40
    W1: 0.0
    W2: 70.4
    label_shape:
    - 352
    - 400
    ratio: 0.2