# for train vae-wgan model using main/train.py on minist dataset
dataset:
  config_file: dataset/gtbbox_gen_fpbbox.yaml
  dataset_class: GtbboxGenFpbbox
logging:
  ckpt_eph_interval: 50
  path: ../output
  suffix: 'GM_model'
model:
  config_file: model/vae_gan.yaml
  model_class: VAEGAN
training:
  device: 'cuda:0'
  epoch: 1000
  gumble_temp: 1.0
  hard_gumble: 0
  rec_weight: 1
  gauss_weight: 1
  categ_weight: 1
  recon_type: bce
  optimizer:
  - name: encoder_opt
    paras:
      lr: 0.0001
    type: Adam
  - name: discriminator_opt
    paras:
      lr: 0.0001
    type: Adam
  trainer_class: GMVaeGanTrainer
  tensorboard_out_path: default