dataset:
  config_file: dataset/actornoise_nuscenes.yaml
  dataset_class: ActorNoiseNuscenesDataset
logging:
  ckpt_eph_interval: 50
  path: ./output/log
  suffix: 'baseline'
model:
  config_file: model/actor_noise.yaml
  model_class: PredictHead
training:
  device: 'cuda:0'
  epoch: 100
  loss_function:
    num_classes: 1
    alpha: 2.0
    beta: 0.01
  optimizer:
    paras:
      lr: 0.001
    type: Adam
  trainer_class: ActornoiseTrainer
  actor_feature_size: 256
  tensorboard_out_path: default
  FP_distribution: False
testing:
  cls_threshold: 0.05
  nms_iou_threshold: 0.5
