name: VAEGANModel
paras:
  use_offline_target_model: True
  submodules:
    discriminator:
      config_file: model/simulator_model/discriminator/mlp_discriminator.yaml
      model_class: MLP
    generator:
      config_file: model/simulator_model/generator/vae.yaml
      model_class: SceneBoxEncoder
    target_model:
      config_file: model/target_model/openpcdet_pvrcnn.yaml
      model_class: OpenPCDetPVRCNN
      model_para_file: /home/xlju/Project/ModelSimulator/model_paras/pv_rcnn/pv_rcnn_8369.pth
    offline_target_model:
      config_file: model/target_model/fake_pvrcnn.yaml
      model_class: FakePVRCNNOnKitti
