name: gaussian_mixture_vae
paras:
  latent_distribution: GaussianMixture
  submodules:
    encoder:
      config_file: model/multi_scale_cnn.yaml
      model_class: MultiScaleCNN
  input_dim: 8800
  gaussian_size: 64
  num_classes: 10
  output_dim: 25