name: VAEGAN
paras:
  submodules:
    discriminator:
      config_file: model/mlp.yaml
      model_class: MLP
    generator:
      config_file: model/GM_vae.yaml
      model_class: GaussianMixtureVae
