CLASS_NAMES: ['Car', 'Pedestrian', 'Cyclist']
DATA_CONFIG:
    _BASE_CONFIG_: ../utils/config/samples/sample4/dataset/openpcd_dataset_related/kitti_dataset.yaml

    DATA_PROCESSOR:
        -   NAME: mask_points_and_boxes_outside_range
            REMOVE_OUTSIDE_BOXES: True

        -   NAME: sample_points
            NUM_POINTS: {
                'train': 16384,
                'test': 16384
            }

        -   NAME: shuffle_points
            SHUFFLE_ENABLED: {
                'train': True,
                'test': False
            }