# for train vae-wgan model using main/train.py on minist dataset
dataset:
  config_file: dataset/minist.yaml
  dataset_class: MinistDataset
logging:
  ckpt_eph_interval: 2
  path: ''
  suffix: ''
model:
  config_file: model/vae_gan.yaml
  model_class: VAEGANModel
training:
  device: 'cuda:0'
  epoch: 100
  optimizer:
  - name: encoder_opt
    paras:
      lr: 0.00005
    type: RMSprop
  - name: discriminator_opt
    paras:
      lr: 0.00005
    type: RMSprop
  trainer_class: VAEWGANTrainer
  n_critic: 5
  weight_clip: 0.01
