# for train vae-wgan model using main/train.py on minist dataset
dataset:
  config_file: dataset/only_box_dataset_fp.yaml
  dataset_class: FpBoxOnlyDataset
logging:
  ckpt_eph_interval: 50
  path: ../output
  suffix: 'only_box_fp'
model:
  config_file: model/vae_gan.yaml
  model_class: VAEGAN
training:
  device: 'cuda:0'
  epoch: 1000
  optimizer:
  - name: encoder_opt
    paras:
      lr: 0.0001
    type: RMSprop
  - name: discriminator_opt
    paras:
      lr: 0.0001
    type: RMSprop
  trainer_class: VAEGANTrainerBoxOnlyFP
  tensorboard_out_path: default